# Generated by cucumber-sinatra. (2011-02-18 13:13:08 -0500)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/401_change.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = FourOhOneChange

class FourOhOneChangeWorld
  include Capybara
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  FourOhOneChangeWorld.new
end
