# Generated by cucumber-sinatra. (2011-02-18 13:13:08 -0500)

ENV['RACK_ENV'] = 'test'
$: << File.expand_path(File.dirname(__FILE__) + '../../../lib')

require '401_change'
require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = FourOhOneChange

class FourOhOneChangeWorld
  include Capybara
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  FourOhOneChangeWorld.new
end

require 'active_record'
ActiveRecord::Base.establish_connection :adapter => 'sqlite3', :database => 'db/test.sqlite3.db'

require 'database_cleaner'
DatabaseCleaner.strategy = :truncation

    # then, whenever you need to clean the DB
